### API LIMITEGASTOS GET
GET http://localhost:8080/api/v1/limitegastos

### API LIMITEGASTOS POST
POST http://localhost:8080/api/v1/limitegastos
Content-Type: application/json

{
    "valorLimite": "500"
}

### API LIMITEGASTOS PUT
PUT http://localhost:8080/api/v1/limitegastos/1
Content-Type: application/json

{
    "valorLimite": "700"
}

### API LIMITEGASTOS DELETE
DELETE http://localhost:8080/api/v1/limitegastos/1