@startuml
package br.univille.projetofabsoftfinancas.entity {
    class Receita {
        - Long id
        - String descricao
        - float valor
        - LocalDate data
        - String tipo
        --
        + Conta conta
        + Cartao cartao
    }

    class Despesa {
        - Long id
        - String descricao
        - float valor
        - LocalDate data
        - String tipo
        --
        + Conta conta
        + Cartao cartao
    }

    class Conta {
        - Long id
        - String numero
        - String agencia
        - String banco
    }

    class Cartao {
        - Long id
        - String numero
        - String cvv
        - String validade
        - String nomeCliente
        - String banco
        - String bandeira
        --
        + Conta conta
    }

    class Investimento {
        - Long id
        - String descricao
        - float valor
        - String prazo
        --
        + Conta conta
    }

    class AlertaPagamento {
        - Long id
        - String descricao
        - LocalDate dataVencimento
        - boolean status
        --
        + Conta conta
        + Cartao cartao
    }

    class Objetivo {
        - Long id
        - String descricao
        - float valorAlvo
        - float progressoAtual
        --
        + Receita receita
        + Investimento investimento
    }

    class LimiteGastos {
        - Long id
        - float valorTotal
        - float valorGasto
    }

    class GraficoDinamico {
        - Long id
        - String tipo
    }

    class RelatorioMensal {
        - Long id
        - String mesAno
    }

    Receita --> Conta : "associada a"
    Receita --> Cartao : "associada a"
    Despesa --> Conta : "associada a"
    Despesa --> Cartao : "associada a"
    Cartao --> Conta : "associado a"
    Investimento --> Conta : "associado a"
    AlertaPagamento --> Conta : "associado a"
    AlertaPagamento --> Cartao : "associado a"
    Objetivo --> Receita : "relacionado a"
    Objetivo --> Investimento : "relacionado a"
}
@enduml